### ISSUE TITLE
Specify that predictions are for kids under 1

### ISSUE THREAD

**Issue by potash** [Chicago/lead-safe-api-docs#10]
This seems to have gone missing from our conversations and documentation but we (as @RaedMan probably remembers) were originally intending to use these predictions for kids under 1. This is both from the CDPH interventions side and also from the modeling side.

So let's add it back in, probably best to do that before we share with Alliance (#9). I will include more details in an issue on the runner repository.

**Comment by tomschenkjr** [comment]
Going to assign this to @RaedMan since it should be mentioned on the sign-up for the service.

**Comment by RaedMan** [comment]
See #1 for draft.

**Comment by tomschenkjr** [comment]
This was addressed and will be accepted in v0.5.0.
