### ISSUE TITLE
Clinical Content for EHRs

### ISSUE THREAD

**Issue by RaedMan** [Chicago/lead-safe-api-docs#16]
Between Nita at Alliance and I, we need to provide the EHR Clinical Content (documents that are uploaded into EHRs) with the following:

- [x] PDF of a Lead FAQ handout in English and Spanish, to be given to patients. It also has the Healthy Homes program financial assistance contact number.
- [x] PDF of a choropleth map of Chicago community areas without Alliance locations, of eBLL over low child opportunity index (a request made by healthcare providers for the entire Alliance Chicago system)

Having these documents available on [Lead Safe API](https://chicago.github.io/lead-safe-api-docs/), whether hospitals are approved for the API access (in which case they will need at least the FAQ), or for hospitals that decide not to enroll for the API, even for smaller facilities that cannot enroll, they all can download these documents as needed and make them available to their patients and healthcare providers.

**Comment by RaedMan** [comment]
This document was approved back in February 2017, but awaiting confirmation that links and telephone numbers are working:  [FAQ English Spanish 02.22.2017.pdf](https://github.com/Chicago/lead-safe-api-docs/files/1400301/FAQ.English.Spanish.02.22.2017.pdf)

**Comment by tomschenkjr** [comment]
I've drafted this sections to download the FAQ. Also have copied the language so it can be viewed as a webpage (instead of HTML). Below are the screenshots:

#### English
![localhost-8000-faq-lead-faq-en- laptop with touch 1](https://user-images.githubusercontent.com/1639121/31806697-4f01ff0a-b52f-11e7-95b1-866c8498e70d.png)

#### Spanish
![localhost-8000-faq-lead-faq-es- laptop with touch](https://user-images.githubusercontent.com/1639121/31806705-54aa0a88-b52f-11e7-87c3-7691d138885c.png)

**Comment by tomschenkjr** [comment]
Just a reminder on this to get the choropleth map and I can finish this one

**Comment by RaedMan** [comment]
I was aiming to update this map, but we can use this as a placeholder until then:
[Lead_Alliance.pdf](https://github.com/Chicago/lead-safe-api-docs/files/1420475/Lead_Alliance.pdf)

**Comment by tomschenkjr** [comment]
I've reorganized the page a little bit to create a "Clinical Resources" section. It contains the map, FAQ, and anything else we want to share with clinicians. Below is a screenshot of how the map appears. Note the left menu that shows the links to see the reorganized section.

![localhost-8000-clinical-resources-elevated-bll-map- laptop with touch 1](https://user-images.githubusercontent.com/1639121/32085559-7ef8c4f8-ba95-11e7-9ee9-b794b18c8fc6.png)

**Comment by RaedMan** [comment]
Looks great! I think the standard EHR term is Clinical Content, but I don't know how well-known that is. I'll loop back after confirming with Alliance.

**Comment by tomschenkjr** [comment]
Ok, I've updated it to "Clinical Content".

**Comment by tomschenkjr** [comment]
I've pushed the documentation over to `dev`. Am closing this for now and can reopen if we get revised maps.
