### ISSUE TITLE
Change "error codes" to "status codes" in documentation

### ISSUE THREAD

**Issue by geneorama** [Chicago/lead-safe-api-docs#18]

**Comment by geneorama** [comment]
We should probably change the other column names as well. 

Here's a summary

Old | New
-- | --
Error Name | Status Class
Error Code |  Status Code
Error Explanation | Status Message

We discussed Status Code in the meeting, but my justification for "status class" comes from [RFC 2616](https://tools.ietf.org/html/rfc2616):

> The first digit of the Status-Code defines the class of response.

**Comment by geneorama** [comment]
Actually @tomschenkjr ... Maybe it's better that we keep it as error codes since these are not official status returns in the HTTP header. My initial question on the name was predicated on thinking that I was testing the status codes.

**Comment by tomschenkjr** [comment]
I think it's fine if we align them. Go ahead and submit a pull request against `dev`.
