### ISSUE TITLE
Test the "apply" page

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/lead-safe-api-docs#26]
We've switched the email address to Healthy Homes, but have not tested it yet. Before "going live", we should test to ensure applying on the page will result in the appropriate emails.

**Comment by tomschenkjr** [comment]
@RaedMan - I've deployed the new documentation for v1.0.0-rc.1. Please test the [apply page](https://chicago.github.io/lead-safe-api-docs/apply/) to make sure you receive a copy of the application to the right email address.

**Comment by RaedMan** [comment]
@tomschenkjr Received this error after completing the form and submitting:
![image](https://user-images.githubusercontent.com/3673571/36743268-7ab26c48-1baf-11e8-97df-cf9b48ab70c5.png)

**Comment by tomschenkjr** [comment]
Ok, thanks! I see the error and will have a fix for the next release.

**Comment by tomschenkjr** [comment]
@RaedMan, I've deployed a fix that caused the issue. I sent a test-submission, but you will need to approve it first. Once you approve it, the submission itself will appear.

After that, please [send a test submission](https://chicago.github.io/lead-safe-api-docs/apply/) yourself to confirm it works.

If you haven't received an email confirmation, let me know.

**Comment by RaedMan** [comment]
@tomschenkjr Received previous submission and tested again, and confirm email receipt of the completed form. Thanks!

**Comment by tomschenkjr** [comment]
@RaedMan - great! The @Chicago/analytics-team  also receive a CC of any submission and also confirm that we received the submission.

We will be removing the "test submission" subject line (#34) once we move the website to it's final location (#32).

Closing this issue now.
