### ISSUE TITLE
Setup automatic deployment to dev website

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/lead-safe-api-docs#32]
The plan is to post the Lead Safe API docs to the city's [Developer website](http://dev.cityofchicago.org) under the "resources" menu. 

To do this, we must "deploy" the documentation from GitHub to a sub-directory on an S3 bucket where `dev.cityofchicago.org` is hosted. The directory must be located within `dev.cityofchicago.org/docs/` directory.

We should use Travis CI to run the necessary `mkdocs build` to compile the inputs to the final website. Travis CI can then "deploy" to the S3 bucket.

See the [Open311 docs](https://github.com/Chicago/open311-api-docs) as an example for this same process.

_Note: the `gh-pages` branch will be deprecated or perhaps just used to test the display of changes to the documentation._

**Comment by tomschenkjr** [comment]
I've prepared the necessary work and is ready on the `dev` branch. I've [switched-on Travis CI for this project](https://travis-ci.org/Chicago/lead-safe-api-docs), but Travis CI will only kick-off when there is a `.travis.yml` file on the `master` branch.

The configuration will build mkDocs and copy the site to http://dev.cityofchicago.org/docs/lead-safe. It's fine if we copy files prior to the official "launch" because it's unlikely to be discovered until we add links from dev.cityofchicago.org to the documentation (see Chicago/dev.cityofchicago.org#50 and Chicago/dev.cityofchicago.org#51)

When we promote this to `master`, we should check that the aforementioned link is working.

**Comment by geneorama** [comment]
Update for status meeting tomorrow; I don't have this done yet, but I'm planning to tackle this next week.
