### ISSUE TITLE
Add "Expected Delivery Date" to API

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/lead-safe-api-docs#35]
In order to support the ability to provide a score for pregnant women, we need a field that can identify whether the record belongs to a pregnant patient. After discussing with @AOCjcarr + team, we determined the best method is to have an "Expected Delivery Date" field (a calendar date).

The idea is if the expected delivery date is in the future, then the patient is a pregnant women and the `date_of_birth` should be ignored (so we don't throw an errant error for "too old"). Not having a date--or the date being in the past--we should then use the `date_of_birth` and `labs` data.

**Comment by tomschenkjr** [comment]
@geneorama - I will leave it to you to create associated issues in other repos for tasks to complete this project. Once we begin work, will ask that you publish the spec for the team to follow. 

This task will be a good step to familiarize yourself with mkdocs.

**Comment by geneorama** [comment]
@tomschenkjr Do you want me to start editing the API docs?  If so, do you want the work done in a branch for the milestone or for just this issue?

Also, I would like to do some cleanup on merged branches and delete `issue1`, `issue2`, `issue14`, and `issue16`, since they've all been merged and to make the 1.0.0-rc.3 work easier to follow.

**Comment by tomschenkjr** [comment]
Per our discussion, feel free to do it for the issue. You can open a pull request against `dev`.

Go ahead and clean-up branches as well.

**Comment by geneorama** [comment]
The actual name of the field that I have is `expected_due_date`, and I've added that to the api docs
