### ISSUE TITLE
Document maximum character limitation in docs

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/lead-safe-api-docs#37]
Our current limitation is 20,000 characters (including whitespaces).

**Comment by geneorama** [comment]
I'm hoping to get more clarity on the performance issues from Sun and George in the coming days before we declare a hard limit. 

Currently there are performance issues with larger files, e.g. files that are more than 10k characters in length.  Although this is a large file for what we're expecting, the technology should be able to handle this file size with no problem.

In fact, each component seems to perform as expected, and it's unclear why the performance issue is cropping up.

**Comment by tomschenkjr** [comment]
@geneorama - Per our discussion today, please set the maximum to 20,000 characters in the documentation. In the future, if we determine that more are needed, we can increase it without breaking existing processes.

**Comment by geneorama** [comment]
Added note in the api docs.
