### ISSUE TITLE
Document values for risk_score_notes

### ISSUE THREAD

**Issue by geneorama** [Chicago/lead-safe-api-docs#38]
@tomschenkjr @RaedMan 

I think we need to document the potential values for `risk_score_notes` so that the test suite and code matches the documentation. I looked in the [API docs](https://github.com/Chicago/lead-safe-api-docs/blob/master/docs/api.md), and didn't see the values.

If I'm missing the documentation, I apologize.

I think that in 1.0.0rc-2 we have two cases:
 - high: "1. Refer for a lead paint visual inspection of home to the Chicago Department of Public Health at 312-747-LEAD(5323)."
 - low: "1. Distribute Lead Frequently Asked Questions. ; 2. Test Blood Lead Levels of every child at 6, 12, 18, 24 and 36 months of age (alternatively, 9, 15, 24 and 36 months)."

I think that in 1.0.0rc-3 we will have three cases:
 - high: (same message)
 - low: (no message / blank, implying that doctors should follow normal protocol)
 - high levels already detected in labs: (what do we put here?)

In the section `Interpreting Risk Levels` we say:

> Elevated lead levels have severe impacts on a child's mental and physical development. When the API identifies elevated blood-lead levels, doctors are highly encouraged to conduct further blood tests

Is this referring to the third case where elevated levels are already detected, or do we intend this to refer to elevated risk of having an elevated BLL in the future?

@avishekrk and I are working on tests and modifications to the runner and we'll use placeholders for the time being. 

Thank you!

**Comment by RaedMan** [comment]
@geneorama thank you for this. I have this question queued for an internal meeting but also, awaiting how the risk ratio will be stated for high. I have another question, if low, what do the healthcare providers see, if notes are blank? I assume it's the score, but does it state low? Thanks.

**Comment by geneorama** [comment]
@RaedMan 
> what do the healthcare providers see

Based on my understanding of our terms and conditions I think the providers are free to show the return values and notes however they want. So, what the provider sees is entirely a function of how the clinic / hospital uses the results from the API in their application.

**Comment by tomschenkjr** [comment]
I suspect the potential issue is not providing _any_ message may not be clear. Instead, should we provide a message which communicates that we estimate the risk level is normal, but otherwise do not provide any other recommendation?

**Comment by tomschenkjr** [comment]
While the above discussion was pertinent, I actually don't agree with the premise of the issue. I don't think we need to detail the messages that will be communicated through the API (as long as it conforms to the data types).

**Comment by geneorama** [comment]
@tomschenkjr makes sense, ok to close?
