### ISSUE TITLE
Response JSON file includes escape characters

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/lead-safe-api-docs#44]
As part of testing, @AOCjcarr informs us:

> We are currently receiving:
```
{
  "items": [
    {
      "result": "{\"risk_score_notes\": \"1. Please follow protocol for lead safety.\", \"errors\": [], \"network_id\": \"AllianceChicago\", \"timestamp\": \"2018-05-08 15:19:05\", \"clinic_id\": \"NN\", \"patient_id\": \"240049\", \"risk_score\": \"0.182835714286\", \"version\": \"1.0.0-rc.3\", \"location_id\": \"NNHS\"}"
    }
  ]
}
```

@geneorama - can you replicate this? Do you see the same in the response documents?

**Comment by geneorama** [comment]
I'm not sure when the escapes appear. I don't see them when I call the python code directly. I do see them in R when I get the response. I'll keep working on it and work with George.

**Comment by geneorama** [comment]
I'm pretty sure this is a single issue related to the quoting mentioned in #45. 

I'm closing this for now, but we can reopen if it turns out to be a separate issue.

**Comment by tomschenkjr** [comment]
Let's keep this open so Sun can remove the backslashes.

**Comment by AOCjcarr** [comment]
Correct, this was resolved with the quoting fix

Thanks,
Jeremy Carr

**Comment by geneorama** [comment]
Thanks Jeremy for confirming! Closing now.
