### ISSUE TITLE
Reach out to Alliance to discuss v0.4.0

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/lead-safe-api-docs#9]
Reach out to Alliance to discuss the changes for v0.4.0 of the API. Get any feedback and raise any issues with the proposed API. CC the project team members when communicating with Alliance so we're aware of the discussion.

**Comment by geneorama** [comment]
@tomschenkjr should I use this link to share with them? https://chicago.github.io/lead-safe-api-docs/

**Comment by tomschenkjr** [comment]
Yeah, I think that’s the easiest to digest.

**Comment by geneorama** [comment]
emailed a few hours ago.
